/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{
    // Docusaurus can create a sidebar automatically from your filesystem structure: each folder creates a sidebar category, and each file creates a doc link.
    type: 'autogenerated',
    // Source folder to generate the sidebar slice from (relative to docs)
    dirName: '.' 
  }],
};

module.exports = sidebars;
